[package]
name = "eyMate"
description = "A linux face recognition like Windows Hello or Howdy"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.95"
clap = "4.5.27"
opencv = { version = "0.94.2", features = ["clang-runtime"] }
pamsm = "0.5.5"
tch = "0.19.0"
v4l = "0.14.0"
