[package]
name = "eyMate"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.27", features = ["derive"] }
opencv = { version = "0.94.2", features = ["clang-runtime"] }
pamsm = "0.5.5"
tch = "0.18.1"
v4l = "0.14.0"
