[package]
name = "eymate-recognition"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
figment = "0.10.19"
opencv = { version = "0.94.2", features = ["clang-runtime"] }
serde = "1.0.218"
tch = "0.19.0"
toml = "0.8.20"
