[package]
name = "pam"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
pamsm = { version = "0.5.5", features = ["libpam"] }
recognition = { path = "../recognition" }
