name: publish
on:
  release:
    types: [published]
env:
  CARGO_TERM_COLOR: always
  LIBTORCH_USE_PYTORCH: 1
jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: pip install -r requirements.txt
      - run: sudo apt install -y makepkg libopencv-dev libpam0g-dev
      - name: Build packages
        run: |
          cargo install cargo-binstall
          cargo binstall cargo-aur
          cargo binstall cargo-deb
          cargo install cargo-generate-rpm --git https://github.com/cat-in-136/cargo-generate-rpm

          cargo build --release

          cargo aur
          cargo deb
          cargo generate-rpm

          makepkg --dir target/cargo-aur/
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: eymate.pkg.tar.zst
          path: target/cargo-aur/*.pkg.tar.zst
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: eymate.deb
          path: target/debian/*.deb
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: eymate.rpm
          path: target/generate-rpm/*.rpm
