name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  LIBTORCH_USE_PYTORCH: 1

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'
    - run: pip install torch torchvision
    - run: sudo apt update
    - run: sudo apt install -y libopencv-dev
    - name: Build
      run: cargo build --verbose
