name: Rust
on:
  pull_request:
  push:
    branches: [main]
env:
  CARGO_TERM_COLOR: always
  LIBTORCH_USE_PYTORCH: 1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libopencv-dev libpam0g-dev
          version: 1.0
      - uses: actions/setup-python@v5
      - run: pip install torch torchvision
      - run: cargo build --verbose
